// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvMrcMRUWDbvw1sGejqlVFylVsU9_ghpw',
    appId: '1:246901090575:android:7bec064c6d9bff8e82f67a',
    messagingSenderId: '246901090575',
    projectId: 'healthe-28eab',
    storageBucket: 'healthe-28eab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoL1pWHIeZgecUU6MB8xmkUKYr_J_o_G4',
    appId: '1:246901090575:ios:8add112ba761e57482f67a',
    messagingSenderId: '246901090575',
    projectId: 'healthe-28eab',
    storageBucket: 'healthe-28eab.appspot.com',
    androidClientId: '246901090575-pdoms4e89jirijtcicba7d6q518pqof6.apps.googleusercontent.com',
    iosClientId: '246901090575-gh2boeg6cel9ddh6u1gam38dd9nivmj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoL1pWHIeZgecUU6MB8xmkUKYr_J_o_G4',
    appId: '1:246901090575:ios:8add112ba761e57482f67a',
    messagingSenderId: '246901090575',
    projectId: 'healthe-28eab',
    storageBucket: 'healthe-28eab.appspot.com',
    androidClientId: '246901090575-pdoms4e89jirijtcicba7d6q518pqof6.apps.googleusercontent.com',
    iosClientId: '246901090575-gh2boeg6cel9ddh6u1gam38dd9nivmj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthe',
  );
}
